// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatProcess(arg1:any):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Session():Promise<any>;
