// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatProcess(arg1) {
  return window['go']['main']['App']['ChatProcess'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RefreshBind(arg1, arg2) {
  return window['go']['main']['App']['RefreshBind'](arg1, arg2);
}

export function Session() {
  return window['go']['main']['App']['Session']();
}

export function StopChat() {
  return window['go']['main']['App']['StopChat']();
}
